opt = vim.opt
vim.o.showtabline = 0
opt.termguicolors = true
opt.number = true
opt.relativenumber = true
opt.hidden = true
opt.fcs = "eob: "
--opt.numberwidth= 5
opt.lazyredraw = true
opt.completeopt = { "menuone", "noselect" }
opt.conceallevel = 0
opt.fileencoding = "utf-8"
opt.mouse = "a"
opt.showmode = false
opt.smartcase = true
opt.smartindent = true
opt.undofile = true
opt.updatetime = 300
opt.expandtab = true
opt.shiftwidth = 4
opt.tabstop = 4
opt.signcolumn = "yes"
opt.wrap = false
opt.laststatus = 3
opt.cmdheight = 0
opt.shell = "/usr/bin/zsh"
opt.cursorline = true
